In [4]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])


print(np.concatenate((a, b), axis=0))
print('\n')
print(np.concatenate((a, b.T), axis=1))
#OR, to do transpose, can also to b.transpose()

[[1 2]
 [3 4]
 [5 6]]


[[1 2 5]
 [3 4 6]]
